"""Create optimal_ranges table

Revision ID: 76d79aced469
Revises: 2e9a229c06f0
Create Date: 2025-04-29 15:25:16.186444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d79aced469'
down_revision = '2e9a229c06f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimal_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=50), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimal_ranges')
    # ### end Alembic commands ###
