"""Refactor SensorData to use parameter_id and value

Revision ID: d40712473da1
Revises: 76d79aced469
Create Date: 2025-04-29 21:38:13.733120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40712473da1'
down_revision = '76d79aced469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Float(), nullable=False))
        batch_op.drop_column('humidity')
        batch_op.drop_column('temperature')
        batch_op.drop_column('pH')
        batch_op.drop_column('light')
        batch_op.drop_column('air_quality')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('air_quality', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('light', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pH', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('humidity', sa.FLOAT(), nullable=True))
        batch_op.drop_column('value')

    # ### end Alembic commands ###
