"""Make resolved_at nullable

Revision ID: f5cc297d77b8
Revises: d40712473da1
Create Date: 2025-04-30 19:20:55.182604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5cc297d77b8'
down_revision = 'd40712473da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.alter_column('resolved_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.alter_column('resolved_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
